### PR TITLE
Adding builder for Wsdl Mock response test step

### PR DESCRIPTION
**Pull request by prakashmrec**

### CODE REVIEW

**Comment by spindelmanne** [comment]
Nice!

**Comment by olensmar** [comment]
perhaps we should have called this "SoapMockResponse" instead ?

**Comment by prakashmrec** [comment]
Good point, I kept the same naming pattern as in Ready! API. I will change in the client, on server side we can still WsdlMockResponse.

**Comment by spindelmanne** [comment]
I agree.

**Pull request merged**
